# Read The Docs config
# - http://docs.readthedocs.io/en/latest/yaml-config.html

# python version
python:
  version: 3.5
  use_system_site_packages: true

requirements_file: requirements-docs.txt

# don't build a PDF (just html)
formats: []
