classname: WaterSupplySectorModel
description: Simulates the optimal operation of the UK water supply system
initial_conditions:
- water_supply_oxford.yml
- reservoirs.yml
inputs:
- name: raininess
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
- name: population
  spatial_resolution: national
  temporal_resolution: annual
  units: people
- name: water_demand
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
interventions:
- water_supply.yml
name: water_supply
outputs:
- name: cost
  spatial_resolution: national
  temporal_resolution: annual
  units: million GBP
- name: energy_demand
  spatial_resolution: national
  temporal_resolution: annual
  units: kWh
- name: water
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
parameters:
- absolute_range: (0, 100)
  default_value: 3
  description: The savings from smart water meters
  name: clever_water_meter_savings
  suggested_range: (3, 10)
  units: '%'
- absolute_range: (0, 1.5)
  default_value: 1.1
  description: The assumed per capita demand for water
  name: per_capita_water_demand
  suggested_range: (1, 1.3)
  units: liter/person
path: models/water_supply.py
