name: water_supply   # model name for internal/logging reference
description: 'Simulates the optimal operation of the UK water
supply system'
path: models/water_supply.py   # path to python file
classname: WaterSupplySectorModel # implements smif.SectorModel
inputs:
- name: precipitation
  dims:
  - country
  dtype: float
  unit: ml
- name: population
  dims:
  - country
  dtype: int
  unit: people
- name: water_demand
  dims:
  - country
  dtype: float
  unit: Ml
- name: reservoir_level
  dims:
  - country
  dtype: float
  unit: Ml
outputs:
- name: cost
  dims:
  - country
  dtype: float
  unit: million GBP
- name: energy_demand
  dims:
  - country
  dtype: float
  unit: kWh
- name: water
  dims:
  - country
  dtype: float
  unit: Ml
- name: reservoir_level
  dims:
  - country
  dtype: float
  unit: Ml
interventions:
  - water_supply.csv
initial_conditions:
  - water_supply_oxford.csv
  - reservoirs.csv
parameters:
- name: clever_water_meter_savings
  description: The savings from smart water meters
  abs_range:
  - 0
  - 100
  exp_range:
  - 3
  - 10
  default: defaults.csv
  dtype: float
  unit: '%'
- name: per_capita_water_demand
  description: The assumed per capita demand for water
  abs_range:
  - 0
  - 1.5
  exp_range:
  - 1
  - 1.3
  default: defaults.csv
  dtype: float
  unit: 'liter/person'
