name: water_supply   # model name for internal/logging reference
description: 'Simulates the optimal operation of the UK water
supply system'
path: models/water_supply.py   # path to python file
classname: WaterSupplySectorModel # implements smif.SectorModel
inputs:
- name: raininess
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
- name: population
  spatial_resolution: national
  temporal_resolution: annual
  units: people
- name: water_demand
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
outputs:
- name: cost
  spatial_resolution: national
  temporal_resolution: annual
  units: million GBP
- name: energy_demand
  spatial_resolution: national
  temporal_resolution: annual
  units: kWh
- name: water
  spatial_resolution: national
  temporal_resolution: annual
  units: Ml
interventions:
  - water_supply.yml
initial_conditions:
  - water_supply_oxford.yml
  - reservoirs.yml
parameters:
- name: clever_water_meter_savings
  description: The savings from smart water meters
  absolute_range: (0, 100)
  suggested_range: (3, 10)
  default_value: 3
  units: '%'
- name: per_capita_water_demand
  description: The assumed per capita demand for water
  absolute_range: (0, 1.5)
  suggested_range: (1, 1.3)
  default_value: 1.1
  units: 'liter/person'
