name: technology
description: Describes the evolution of technology
provides:
  - name: smart_meter_savings
    description: The savings from smart meters
    dtype: float
    unit: '%'
  - name: clever_water_meter_savings
    description: The savings from smart water meters
    dtype: float
    unit: '%'
  - name: per_capita_water_demand
    description: The assumed per capita demand for water
    dtype: float
    unit: liter/person
variants:
  - name: high_tech_dsm
    description: High penetration of SMART technology on the demand side
    data:
      smart_meter_savings: high_tech_dsm.csv
      clever_water_meter_savings: high_tech_dsm.csv
      per_capita_water_demand: high_tech_dsm.csv
