name: technology
description: Describes the evolution of technology
sos_model: energy_water
provides:
  energy_demand:
    - name: smart_meter_savings
  water_supply:
    - name: clever_water_meter_savings
    - name: per_capita_water_demand
variants:
  - name: high_tech_dsm
    description: High penetration of SMART technology on the demand side
    data:
      smart_meter_savings: high_tech_dsm.csv
      clever_water_meter_savings: high_tech_dsm.csv
      per_capita_water_demand: high_tech_dsm.csv
