decision_module: ''
description: Combined energy and water under central scenario
name: 20170918_energy_water
narratives:
  technology:
  - High Tech Demand Side Management
scenarios:
  population: Central Population (Medium)
  rainfall: Central Rainfall
sos_model: energy_water
stamp: '2017-09-18T12:53:23+00:00'
timesteps:
- 2010
- 2015
- 2020
