name = "energy_water"
description = "The future supply and demand of energy and water for the UK"
scenarios = [
    "population",
    "climate",
    "reservoir_level",
    "water_sector_energy_demand",
]
sector_models = [
    "water_supply",
    "energy_demand",
]

[[narratives]]
name = "technology"
description = "Describes the evolution of technology"
sos_model = "energy_water"

[narratives.provides]
energy_demand = [
    "smart_meter_savings",
]
water_supply = [
    "clever_water_meter_savings",
    "per_capita_water_demand",
]

[[narratives.variants]]
name = "high_tech_dsm"
description = "High penetration of SMART technology on the demand side"

[narratives.variants.data]
smart_meter_savings = "high_tech_dsm"
clever_water_meter_savings = "high_tech_dsm"
per_capita_water_demand = "high_tech_dsm"

[[scenario_dependencies]]
source = "climate"
source_output = "precipitation"
sink = "water_supply"
sink_input = "precipitation"

[[scenario_dependencies]]
source = "population"
source_output = "population"
sink = "water_supply"
sink_input = "population"

[[scenario_dependencies]]
source = "population"
source_output = "population"
sink = "energy_demand"
sink_input = "population"

[[scenario_dependencies]]
source = "reservoir_level"
source_output = "reservoir_level"
sink = "water_supply"
sink_input = "reservoir_level"

[[scenario_dependencies]]
source = "water_sector_energy_demand"
source_output = "energy_demand"
sink = "energy_demand"
sink_input = "energy_demand"

[[model_dependencies]]
source = "energy_demand"
source_output = "water_demand"
sink = "water_supply"
sink_input = "water_demand"

[[model_dependencies]]
source = "water_supply"
source_output = "reservoir_level"
sink = "water_supply"
sink_input = "reservoir_level"
timestep = "PREVIOUS"
