name: population
description: Growth in UK population
provides:
  - name: population
    description: ''
    dims:
      - country
    dtype: int
    unit: people
  - name: population_density
    description: ''
    dims:
      - country
    dtype: float
    unit: people/km²
variants:
  - name: population_low
    description: Central Population (Low)
    data:
      population: population_low
      population_density: population_density_low
  - name: population_med
    description: Central Population (Medium)
    data:
      population: population_med
      population_density: population_density_med
  - name: population_high
    description: Central Population (High)
    data:
      population: population_high
      population_density: population_density_high
